// Node identifiers for edge matching — keep in sync with hexmap/src/data/topology.js
module.exports = [
  { id: 'cyno', name: 'Cyno', meta: {} },
  { id: 'kazuha', name: 'Kazuha', meta: {} },
  { id: 'venti', name: 'Venti', meta: { lokiLabel: 'venti' } },
  { id: 'nahida', name: 'Nahida', meta: { lokiLabel: 'nahida' } },
  { id: 'furina', name: 'Furina', meta: { lokiLabel: 'furina' } },
  { id: 'raiden', name: 'Raiden', meta: { lokiLabel: 'raiden' } },
  { id: 'heizou', name: 'Heizou', meta: { lokiLabel: 'heizou' } },
  { id: 'zhongli', name: 'Zhongli', meta: { lokiLabel: 'zhongli' } },
  { id: 'noelle', name: 'Noelle', meta: { lokiLabel: 'noelle' } },
  { id: 'navia',       name: 'Navia',       meta: { lokiLabel: 'navia',       pveId: 'qemu/106' } },
  { id: 'kirara',      name: 'Kirara',      meta: { lokiLabel: 'kirara',      pveId: 'lxc/103'  } },
  { id: 'chiori',      name: 'Chiori',      meta: { lokiLabel: 'chiori',      pveId: 'qemu/107' } },
  { id: 'shenhe',      name: 'Shenhe',      meta: { lokiLabel: 'shenhe',      pveId: 'qemu/108' } },
  { id: 'lyney',       name: 'Lyney',       meta: { lokiLabel: 'lyney',       pveId: 'lxc/104'  } },
  { id: 'lynette',     name: 'Lynette',     meta: { lokiLabel: 'lynette',     pveId: 'lxc/105'  } },
  { id: 'neuvillette', name: 'Neuvillette', meta: { lokiLabel: 'neuvillette', pveId: 'qemu/100' } },
  { id: 'ningguang',   name: 'Ningguang',   meta: { lokiLabel: 'ningguang',   pveId: 'lxc/200'  } },
  { id: 'yelan',       name: 'Yelan',       meta: { lokiLabel: 'yelan',       pveId: 'lxc/201'  } },
  { id: 'argocd', name: 'ArgoCD', meta: { lokiLabel: 'argocd-server' } },
  { id: 'infisical', name: 'Infisical', meta: { lokiLabel: 'infisical-infisical-standalone-infisical' } },
  { id: 'infisical-redis', name: 'Infisical Redis', meta: { lokiLabel: 'redis-master' } },
  { id: 'infisical-operator', name: 'Infisical Operator', meta: { lokiLabel: 'secrets-operato-controller-manager' } },
  { id: 'traefik', name: 'Traefik', meta: { lokiLabel: 'traefik' } },
  { id: 'redis', name: 'Redis', meta: { lokiLabel: 'redis' } },
  { id: 'authentik', name: 'Authentik', meta: { lokiLabel: 'authentik', authentikSlug: 'authentik' } },
  { id: 'vaultwarden', name: 'Vaultwarden', meta: { lokiLabel: 'vaultwarden', authentikSlug: 'vaultwarden' } },
  { id: 'it-tools', name: 'IT Tools', meta: { lokiLabel: 'it-tools', authentikSlug: 'tools' } },
  { id: 'family-portal', name: 'Family Portal', meta: { lokiLabel: 'family-portal', authentikSlug: 'family-portal' } },
  { id: 'actual', name: 'Actual Budget', meta: { lokiLabel: 'actual', authentikSlug: 'actual' } },
  { id: 'surmai', name: 'Surmai', meta: { lokiLabel: 'surmai', authentikSlug: 'surmai' } },
  { id: 'dailytxt', name: 'DailyTXT', meta: { lokiLabel: 'dailytxt', authentikSlug: 'dailyitxt' } },
  { id: 'nocobase', name: 'NocoBase', meta: { lokiLabel: 'nocobase', authentikSlug: 'nocobase' } },
  { id: 'appsmith', name: 'Appsmith', meta: { lokiLabel: 'appsmith', authentikSlug: 'appsmith' } },
  { id: 'mathesar', name: 'Mathesar', meta: { lokiLabel: 'mathesar', authentikSlug: 'mathesar' } },
  { id: 'nocodb', name: 'NocoDB', meta: { lokiLabel: 'nocodb', authentikSlug: 'nocodb' } },
  { id: 'outline', name: 'Outline', meta: { lokiLabel: 'outline', authentikSlug: 'outline' } },
  { id: 'n8n', name: 'n8n', meta: { lokiLabel: 'n8n', authentikSlug: 'n8n' } },
  { id: 'wordpress', name: 'WordPress', meta: { lokiLabel: 'wordpress', authentikSlug: 'wordpress' } },
  { id: 'termix', name: 'Termix', meta: { lokiLabel: 'termix', authentikSlug: 'termix' } },
  { id: 'onlyoffice', name: 'OnlyOffice', meta: { lokiLabel: 'onlyoffice', authentikSlug: 'onlyoffice' } },
  { id: 'jellyfin', name: 'Jellyfin', meta: { lokiLabel: 'jellyfin', authentikSlug: 'jellyfin' } },
  { id: 'filebrowser', name: 'File Browser', meta: { lokiLabel: 'filebrowser', authentikSlug: 'filebrowser' } },
  { id: 'tdarr', name: 'Tdarr', meta: { lokiLabel: 'tdarr', authentikSlug: 'tdarr' } },
  { id: 'mediamtx', name: 'MediaMTX', meta: { lokiLabel: 'mediamtx', authentikSlug: 'mediamtx' } },
  { id: 'wg-easy', name: 'wg-easy', meta: { lokiLabel: 'wg-easy', authentikSlug: 'wg-easy' } },
  { id: 'gitea', name: 'Gitea', meta: { lokiLabel: 'gitea', authentikSlug: 'gitea' } },
  { id: 'nextcloud', name: 'Nextcloud', meta: { lokiLabel: 'nextcloud', authentikSlug: 'nextcloud' } },
  { id: 'immich', name: 'Immich', meta: { lokiLabel: 'immich', authentikSlug: 'immich' } },
  { id: 'bookstack', name: 'BookStack', meta: { lokiLabel: 'bookstack', authentikSlug: 'bookstack' } },
  { id: 'uptime-kuma', name: 'Uptime Kuma', meta: { lokiLabel: 'uptime-kuma', authentikSlug: 'uptime' } },
  { id: 'dockhand', name: 'Dockhand', meta: { lokiLabel: 'dockhand' } },
];
